// Curated parenting welfare services. Static reference data so the skill works
// fully offline. Figures intentionally describe eligibility/process rather than
// exact won amounts, which change annually; users must confirm on the official
// site before applying.

const CURATED_SERVICES = Object.freeze([
  {
    serviceId: "child-allowance",
    title: "아동수당",
    category: "현금지원",
    agency: "보건복지부",
    eligibility: "만 8세 미만(0~95개월) 모든 아동",
    requiredDocs: ["아동수당 지급 신청서", "신청자 신분증", "통장 사본"],
    officialUrl: "https://www.bokjiro.go.kr/",
    contact: "보건복지상담센터 129",
    deadline: "상시 신청(출생 후 60일 이내 신청 시 출생월부터 소급)",
  },
  {
    serviceId: "parental-benefit",
    title: "부모급여",
    category: "현금지원",
    agency: "보건복지부",
    eligibility: "만 0~1세(0~23개월) 아동을 양육하는 가구",
    requiredDocs: ["부모급여 신청서", "신청자 신분증", "통장 사본"],
    officialUrl: "https://www.bokjiro.go.kr/",
    contact: "보건복지상담센터 129",
    deadline: "상시 신청(출생 후 60일 이내 신청 시 출생월부터 소급)",
  },
  {
    serviceId: "child-care-allowance",
    title: "양육수당",
    category: "현금지원",
    agency: "보건복지부",
    eligibility: "어린이집·유치원·종일제 아이돌봄을 이용하지 않는 가정 양육 아동",
    requiredDocs: ["양육수당 신청서", "신청자 신분증", "통장 사본"],
    officialUrl: "https://www.bokjiro.go.kr/",
    contact: "보건복지상담센터 129",
    deadline: "상시 신청",
  },
  {
    serviceId: "home-care-allowance",
    title: "가정양육수당",
    category: "현금지원",
    agency: "보건복지부",
    eligibility: "어린이집·유치원 미이용 가정에서 양육하는 만 86개월 미만 아동",
    requiredDocs: ["가정양육수당 신청서", "신청자 신분증", "통장 사본"],
    officialUrl: "https://www.bokjiro.go.kr/",
    contact: "보건복지상담센터 129",
    deadline: "상시 신청",
  },
  {
    serviceId: "idolbom",
    title: "아이돌봄서비스",
    category: "돌봄서비스",
    agency: "여성가족부",
    eligibility: "만 12세 이하 아동을 둔 맞벌이 등 양육공백 가정(소득기준 차등 지원)",
    requiredDocs: ["아이돌봄 서비스 신청서", "맞벌이 등 증빙서류", "건강보험료 납부확인서"],
    officialUrl: "https://www.idolbom.go.kr/",
    contact: "아이돌봄 대표전화 1577-2514",
    deadline: "상시 신청(이용 전 회원가입 및 정부지원 판정 필요)",
  },
  {
    serviceId: "after-school",
    title: "방과후학교(돌봄교실)",
    category: "돌봄서비스",
    agency: "교육부",
    eligibility: "초등학교 재학생(돌봄교실은 저학년 및 맞벌이·저소득 우선)",
    requiredDocs: ["방과후·돌봄교실 신청서", "맞벌이 등 증빙서류"],
    officialUrl: "https://www.gov.kr/",
    contact: "재학 중인 학교 행정실",
    deadline: "학기 초 학교별 신청 일정에 따름",
  },
  {
    serviceId: "childcare-fee",
    title: "보육료(어린이집)",
    category: "이용권/바우처",
    agency: "보건복지부",
    eligibility: "어린이집을 이용하는 영유아",
    requiredDocs: ["보육료 지원 신청서", "신청자 신분증", "아이행복카드"],
    officialUrl: "https://www.bokjiro.go.kr/",
    contact: "보건복지상담센터 129",
    deadline: "상시 신청(이용 전 아이행복카드 발급 필요)",
  },
  {
    serviceId: "preschool-tuition",
    title: "유아학비(유치원)",
    category: "이용권/바우처",
    agency: "교육부",
    eligibility: "유치원을 이용하는 만 3~5세 누리과정 대상 유아",
    requiredDocs: ["유아학비 지원 신청서", "신청자 신분증", "아이행복카드"],
    officialUrl: "https://www.childcare.go.kr/",
    contact: "보건복지상담센터 129",
    deadline: "상시 신청(이용 전 아이행복카드 발급 필요)",
  },
]);

module.exports = { CURATED_SERVICES };
